service: serverless-ssr

plugins:
  - serverless-nextjs-plugin
  - serverless-offline
  - serverless-sentry

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  sentry:
    dsn: ${env:SENTRY_DSN}
    organization: cuistotducoin
    project: front
  serverless-nextjs:
    nextConfigDir: ./
    pageConfig:
      workshop:
        events:
          - http:
              path: workshop
              request:
                parameters:
                  paths:
                    workshopId: true

provider:
  name: aws
  stage: ${env:STAGE}
  runtime: nodejs8.10
  region: ${env:AWS_REGION_IRELAND}
  endpointType: regional
  environment:
    AWS_REGION_IRELAND: ${env:AWS_REGION_IRELAND}
    AWS_USERPOOL_ID: ${env:AWS_USERPOOL_ID}
    AWS_IDENTITY_POOL_ID: ${env:AWS_IDENTITY_POOL_ID}
    AWS_STORE_BUCKET: ${env:AWS_STORE_BUCKET}
    AWS_APP_CLIENT_ID: ${env:AWS_APP_CLIENT_ID}
    GRAPHQL_API_URL: ${env:GRAPHQL_API_URL}
    GUEST_USERNAME: ${env:GUEST_USERNAME}
    GUEST_PASSWORD: ${env:GUEST_PASSWORD}
    ALGOLIASEARCH_SEARCH_APP_ID: ${env:ALGOLIASEARCH_SEARCH_APP_ID}
    ALGOLIASEARCH_SEARCH_KEY: ${env:ALGOLIASEARCH_SEARCH_KEY}
    ALGOLIASEARCH_PLACES_APP_ID: ${env:ALGOLIASEARCH_PLACES_APP_ID}
    ALGOLIASEARCH_PLACES_KEY: ${env:ALGOLIASEARCH_PLACES_KEY}
    SENTRY_DSN: ${env:SENTRY_DSN}
    SLS_DEBUG: "*"

package:
  exclude:
    - ./**
