service: serverless-ssr

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-sentry
  - serverless-stage-manager

frameworkVersion: ">=1.21.0 <2.0.0"

custom:
  stages:
    - development
    - staging
    - production
  apigwBinary:
    types:
      - '*/*'
  sentry:
    dsn: ${env:SENTRY_DSN}
    organization: cuistotducoin
    project: front

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'development'}
  region: eu-west-1
  deploymentBucket: ${env:AWS_DEPLOYMENT_BUCKET}
  endpointType: regional
  environment:
    AWS_DOMAIN: ${env:AWS_DOMAIN}
    AWS_REGION_IRELAND: ${env:AWS_REGION_IRELAND}
    AWS_DEPLOYMENT_BUCKET: ${env:AWS_DEPLOYMENT_BUCKET}
    AWS_USERPOOL_ID: ${env:AWS_USERPOOL_ID}
    AWS_IDENTITY_POOL_ID: ${env:AWS_IDENTITY_POOL_ID}
    AWS_STORE_BUCKET: ${env:AWS_STORE_BUCKET}
    AWS_APP_CLIENT_ID: ${env:AWS_APP_CLIENT_ID}
    GRAPHQL_API_URL: ${env:GRAPHQL_API_URL}
    GUEST_USERNAME: ${env:GUEST_USERNAME}
    GUEST_PASSWORD: ${env:GUEST_PASSWORD}
    ALGOLIASEARCH_SEARCH_APP_ID: ${env:ALGOLIASEARCH_SEARCH_APP_ID}
    ALGOLIASEARCH_SEARCH_KEY: ${env:ALGOLIASEARCH_SEARCH_KEY}
    ALGOLIASEARCH_PLACES_APP_ID: ${env:ALGOLIASEARCH_PLACES_APP_ID}
    ALGOLIASEARCH_PLACES_KEY: ${env:ALGOLIASEARCH_PLACES_KEY}
    SENTRY_DSN: ${env:SENTRY_DSN}
    SLS_DEBUG: "*"

package:
  exclude:
    - ./**
  include:
    - build/**

functions:
  ssr:
    timeout: 30
    handler: build/lambda.handler
    events:
      - http:
          method: any
          cors: true
          path: /{proxy+}